
export const CURATED_SEEDS: Record<string, string[]> = {

    'shaving': [
        // HEAD TERMS
        "razor", "trimmer", "shaving cream", "shaving foam", "aftershave",
        "electric shaver", "safety razor", "razor blades", "shaving gel",
        "shaving brush", "pre shave oil", "shaving kit", "razor cartridge",
        "shaving soap", "straight razor", "disposable razor",
        // BRANDS
        "gillette razor", "gillette mach3", "gillette fusion", "gillette guard",
        "gillette shaving cream", "gillette foam", "gillette cartridge",
        "gillette venus", "gillette proglide", "gillette guard cartridge price",
        "philips trimmer", "philips shaver", "philips one blade",
        "philips trimmer 3000", "philips trimmer 5000", "philips norelco",
        "braun shaver", "braun series 3", "braun series 5",
        "panasonic trimmer", "panasonic shaver",
        "bombay shaving company", "bombay shaving company razor",
        "ustraa trimmer", "ustraa razor", "ustraa shaving foam",
        "havells trimmer", "havells trimmer price",
        "beardo trimmer", "beardo shaving cream",
        "the man company razor", "park avenue shaving cream",
        "vi john shaving cream", "old spice aftershave",
        "supermax razor", "supermax blades",
        "zlade razor", "zlade shaving kit",
        // BUYING INTENT
        "best razor for men", "best trimmer under 1000", "best trimmer under 2000",
        "best trimmer under 500", "best trimmer under 1500",
        "best electric shaver india", "best safety razor india",
        "trimmer price", "razor price", "gillette razor price",
        "trimmer for men", "trimmer for beard", "shaving kit price",
        "electric shaver price", "razor blades price",
        "buy trimmer online", "buy razor online", "buy shaving kit online",
        "shaving cream price", "aftershave price",
        "trimmer combo offer", "razor refill pack",
        "shaving kit for men price", "best shaving kit under 500",
        "braun trimmer price india", "shaving machine for men",
        "beard trimmer combo offer",
        // COMPARISON
        "trimmer vs razor", "gillette vs bombay shaving company",
        "manual razor vs electric", "safety razor vs cartridge razor",
        "philips vs braun trimmer", "shaving foam vs gel",
        "wet shave vs dry shave", "electric shaver vs manual",
        "gillette fusion vs mach3", "zero gap trimmer review",
        // PROBLEM / HOW-TO
        "how to shave", "how to shave properly", "how to shave without razor bumps",
        "shaving tips for men", "razor burn treatment", "razor burn remedy",
        "ingrown hair after shaving", "smooth shave tips",
        "shaving for sensitive skin", "razor bumps on neck",
        "how to prevent razor bumps", "how to use beard trimmer",
        "how often should men shave", "what is aftershave used for",
        "how to avoid cuts while shaving", "how to trim beard at home",
        "how to reduce shaving irritation", "how to stop shaving irritation",
        "best aftershave for cuts", "how to clean trimmer blades",
        // LONG TAIL
        "double edge razor", "electric trimmer for men", "body trimmer for men",
        "nose trimmer", "ear trimmer", "manscaping trimmer",
        "body groomer for men", "back hair trimmer",
        "waterproof trimmer", "cordless trimmer",
        "trimmer with multiple attachments", "precision trimmer",
        "rotary shaver", "foil shaver", "shaving set gift",
        "luxury shaving kit", "shaving stand", "shaving bowl",
        "alum block", "styptic pencil", "razor bumps cream",
        "bump patrol", "ingrown hair serum",
        "shaving cream for sensitive skin", "electric shaver for men",
        "gillette razor price india", "shaving kit for beginners",
        "razor cartridge refill", "safety razor india", "aftershave balm for men",
        // INFORMATIONAL
        "benefits of shaving foam", "types of razors", "shaving history",
        "best time to shave", "should men shave daily"
    ],

    'beard': [
        "beard oil", "beard growth oil", "beard trimmer", "beard balm",
        "beard wash", "beard comb", "beard straightener", "beard wax",
        "beard color", "beard dye", "beard softener", "mustache wax",
        "beard serum", "beard roller", "beard brush", "beard conditioner",
        "beard growth serum", "beard styling cream", "beard butter",
        "beard shampoo", "beard mask", "beard growth cream",
        // BRANDS
        "beardo beard oil", "beardo beard wash", "beardo beard serum",
        "beardo beard growth oil", "beardo ultraglow",
        "ustraa beard oil", "ustraa beard growth oil", "ustraa beard wash",
        "the man company beard oil", "the man company beard wash",
        "bombay shaving company beard oil", "philips beard trimmer",
        "man matters beard oil", "man matters beard growth",
        "vedix beard oil", "wild stone beard oil",
        "park avenue beard oil", "set wet beard oil",
        "braun beard trimmer", "wahl beard trimmer",
        "philips bt3000", "philips bt5000",
        // BUYING INTENT
        "best beard oil", "best beard oil for growth", "best beard oil india",
        "best beard trimmer", "best beard trimmer under 1000",
        "best beard trimmer under 2000", "best beard trimmer under 500",
        "beard oil price", "beard growth kit", "beard grooming kit",
        "beard oil for men price", "buy beard oil online",
        "beard trimmer price", "beard growth kit price",
        "beard combo pack", "beard care kit for men",
        "best beard color for men", "beard straightener price",
        // COMPARISON
        "beardo vs ustraa", "beardo vs man company",
        "beard oil vs beard balm", "beard oil vs coconut oil",
        "minoxidil vs beard oil", "derma roller vs minoxidil",
        // PROBLEM / HOW-TO
        "how to grow beard faster", "how to grow beard naturally",
        "patchy beard solution", "beard growth tips",
        "beard dandruff treatment", "beard itch remedy",
        "grey beard dye for men", "minoxidil for beard",
        "derma roller for beard", "how to shape beard",
        "how to trim beard at home", "beard trimming tips",
        "patchy beard fix", "thin beard solution",
        "beard not growing evenly", "how to soften beard",
        "beard growth home remedies", "foods for beard growth",
        "biotin for beard growth", "vitamins for beard growth",
        // STYLES & LONG TAIL
        "beard styles for men", "short beard styles", "long beard styles",
        "goatee styles", "stubble beard", "french beard",
        "beard styles for round face", "beard styles for oval face",
        "handlebar mustache", "soul patch",
        "beard oil benefits", "coconut oil for beard",
        "castor oil for beard", "jojoba oil for beard",
        "beard transplant cost india", "beard implant"
    ],

    'hair-styling': [
        "hair wax", "hair gel", "pomade", "hair cream for men", "hair spray for men",
        "hair clay", "hair mousse for men", "hair serum for men",
        "hair paste", "hair putty", "texturizing spray", "volumizing powder",
        "dry shampoo for men", "sea salt spray", "hair styling products",
        "strong hold gel", "matte finish wax", "wet look gel",
        "hair styling cream for men", "anti frizz serum men",
        // BRANDS
        "set wet hair gel", "set wet hair wax", "set wet ultra hold",
        "gatsby hair wax", "gatsby moving rubber", "gatsby styling wax",
        "beardo hair wax", "beardo hair cream", "beardo hair serum",
        "ustraa hair wax", "ustraa hair cream",
        "park avenue hair gel", "park avenue cool blue",
        "schwarzkopf hair wax", "schwarzkopf got2b",
        "loreal hair gel", "loreal hair wax",
        "brylcreem", "brylcreem hair cream",
        "tresemme hair spray", "dove hair mousse men",
        "garnier men styling", "american crew pomade",
        "axe hair styling", "old spice hair wax",
        // BUYING INTENT
        "best hair wax for men", "best hair gel for men",
        "best pomade india", "best hair clay for men",
        "hair wax price", "hair gel price", "pomade price",
        "best hair styling product for men", "buy hair wax online",
        "hair wax under 200", "hair wax under 500",
        "best matte wax india", "hair gel combo offer",
        "hair styling kit for men",
        // COMPARISON
        "hair wax vs gel", "pomade vs wax", "clay vs wax",
        "matte vs glossy wax", "set wet vs gatsby",
        "gel vs cream for hair", "mousse vs gel",
        // HAIRSTYLE INTENT (massive volume)
        "hairstyle for men", "hairstyle for round face men",
        "hairstyle for thin hair men", "hairstyle for boys",
        "how to style hair men", "hairstyle for oval face men",
        "hairstyle for long hair men", "hairstyle for curly hair men",
        "hairstyle for forehead men", "latest hairstyle for men",
        "korean hairstyle men", "fade hairstyle", "undercut hairstyle",
        "quiff hairstyle men", "pompadour hairstyle",
        "slick back hairstyle", "messy hairstyle men",
        "french crop hairstyle", "textured crop men",
        "buzz cut", "crew cut", "taper fade",
        // PROBLEM
        "hair gel side effects", "does hair wax cause hair fall",
        "hair styling without damage", "natural hair wax",
        "hair wax for thin hair", "how to wash off hair wax",
        "hair wax alternative", "safe hair gel for daily use",
        // LONG TAIL
        "hair wax for short hair", "hair styling for wedding",
        "volumizing hair powder men", "matte clay for men",
        "fiber wax for men", "water based pomade",
        "pre styler for men", "blow dry products men",
        "heat protectant for men", "hair straightening cream men"
    ],

    'sexual-wellness': [
        "condom", "condoms", "condom price", "condom pack",
        "condom online", "condom size chart", "condom types",
        "dotted condom", "ribbed condom", "extra thin condom",
        "flavoured condom", "ultra thin condom", "extra large condom",
        "delay condom", "textured condom", "latex free condom",
        // BRANDS
        "durex condom", "durex air", "durex mutual climax",
        "durex extra thin", "durex price",
        "manforce condom", "manforce price", "manforce 3 in 1",
        "skore condom", "skore champion", "skore pineapple",
        "kamasutra condom", "kamasutra dotted",
        "moods condom", "moods dotted", "moods all night",
        "playgard condom", "kohinoor condom",
        "bold care", "bold care delay spray",
        "man matters", "man matters delay spray",
        // LUBRICANT
        "lubricant", "lube", "water based lubricant", "durex lube",
        "ky jelly", "intimate lubricant", "silicon based lubricant",
        "lubricant gel", "lubricant price", "best lubricant for men",
        // PERFORMANCE
        "delay spray", "delay spray for men", "stamina tablets",
        "shilajit", "shilajit capsule", "shilajit gold",
        "ashwagandha for men", "ashwagandha capsule",
        "testosterone booster", "testosterone booster india",
        "stamina booster", "performance enhancer",
        "long lasting spray", "climax delay",
        "sexual stamina tips", "premature ejaculation solution",
        // BUYING INTENT
        "best condom brand in india", "condom variety pack",
        "best delay spray", "buy condom online",
        "condom combo pack", "durex combo offer",
        "best condom for first time", "best thin condom india",
        "delay spray price", "shilajit price",
        // INFORMATION
        "how to use condom", "condom effectiveness",
        "condom side effects", "birth control methods",
        "sexual health tips", "how to last longer",
        "premature ejaculation causes", "testosterone levels normal",
        "benefits of shilajit", "ashwagandha benefits for men"
    ],

    'intimate-hygiene': [
        "intimate wash for men", "intimate wash", "intimate hygiene wash",
        "ball powder", "ball deodorant", "ball wash",
        "anti chafing cream", "anti chafing powder",
        "groin powder", "crotch care", "below the belt grooming",
        "mens hygiene products", "intimate area cream",
        "intimate area whitening", "intimate area wash",
        // BRANDS
        "pee safe intimate wash", "pee safe intimate wash for men",
        "man matters intimate wash", "man matters hygiene wash",
        "the man company intimate wash", "svish intimate wash",
        "ustraa intimate wash", "below the belt",
        "manscaped", "manscaped products",
        "letsshave intimate wash", "spruce intimate wash",
        "bold care intimate wash", "cinthol intimate wash",
        // PROBLEM INTENT
        "jock itch treatment", "jock itch cream", "jock itch remedy",
        "jock itch medicine", "jock itch powder",
        "groin sweat solution", "groin rash treatment",
        "anti fungal cream", "anti fungal cream for men",
        "dark inner thighs", "dark inner thighs remedy",
        "fungal infection treatment", "itching in private area male",
        "itching in groin area", "ringworm treatment groin",
        "prickly heat groin", "heat rash groin",
        "chafing between thighs", "thigh chafing remedy",
        "body odour intimate area", "sweat rash treatment",
        // BUYING INTENT
        "best intimate wash for men", "intimate wash price",
        "intimate hygiene products for men", "buy intimate wash online",
        "best anti chafing cream india", "ball powder price",
        // LONG TAIL
        "body powder for men", "sweat absorbing powder",
        "manscaping products", "male grooming below belt",
        "intimate hygiene tips men", "personal hygiene for men",
        "how to clean intimate area male", "intimate area dark skin treatment",
        "anti bacterial wash men", "ph balanced wash men",
        "intimate deodorant men", "fresh balls",
        "talc for groin", "anti odour spray intimate"
    ],

    'hair-colour': [
        "hair colour for men", "hair color for men", "hair dye for men",
        "grey hair colour", "black hair dye", "brown hair colour men",
        "beard colour for men", "hair colour shampoo",
        "hair colour cream", "permanent hair colour", "temporary hair colour",
        "semi permanent hair colour", "ammonia free hair colour",
        "natural hair dye", "henna for men", "herbal hair colour",
        "instant hair colour", "hair colour spray",
        // BRANDS
        "garnier hair colour men", "garnier color naturals men",
        "loreal hair colour men", "loreal casting creme",
        "godrej expert hair colour", "godrej nupur henna",
        "indica hair colour", "indica easy hair colour",
        "just for men hair colour", "just for men beard colour",
        "streax hair colour", "streax insta colour",
        "bigen hair colour", "bigen speedy colour",
        "schwarzkopf hair colour", "schwarzkopf men perfect",
        "patanjali kesh kanti colour", "revlon hair colour men",
        "vegetal hair colour", "khadi natural hair colour",
        // BUYING INTENT
        "best hair colour for men", "best hair colour for grey hair",
        "hair colour price", "hair dye price for men",
        "ammonia free hair colour price", "natural hair dye price",
        "best beard colour", "best hair colour without side effects",
        "best grey coverage hair colour", "buy hair colour online",
        "hair colour combo offer", "hair colour kit for men",
        // HOW-TO
        "how to colour hair at home men", "how to cover grey hair",
        "how to apply hair colour at home", "how to dye beard at home",
        "how to remove hair colour", "how long does hair colour last",
        "hair colour tips at home", "diy hair colouring men",
        // PROBLEM
        "grey hair solution", "premature grey hair treatment",
        "white hair to black permanently", "premature greying causes",
        "grey hair at 20", "grey hair vitamins", "grey hair reversal",
        "side effects of hair colour", "ammonia free safe hair colour",
        "hair colour allergy treatment", "scalp sensitive hair colour",
        // LONG TAIL
        "henna for men hair", "indigo hair dye",
        "coffee hair dye", "natural grey coverage",
        "highlights for men", "blonde hair colour men",
        "burgundy hair colour men", "ash grey hair colour men",
        "platinum blonde men", "copper hair colour men"
    ],

    'face-care': [
        "face wash for men", "moisturizer for men", "sunscreen for men",
        "face cream for men", "face scrub for men", "face serum for men",
        "face mask for men", "anti acne cream", "face toner for men",
        "bb cream for men", "cc cream for men", "face primer for men",
        "lip balm for men", "under eye cream for men", "face pack for men",
        "night cream for men", "anti aging cream for men",
        "pimple cream", "acne gel", "spot corrector",
        // BRANDS
        "nivea men face wash", "nivea men moisturizer",
        "garnier men face wash", "garnier men acno fight",
        "ponds men face wash", "ponds men cream",
        "loreal men face wash", "loreal men moisturizer",
        "cetaphil face wash", "cetaphil moisturizer",
        "minimalist sunscreen", "minimalist vitamin c",
        "derma co face serum", "derma co sunscreen",
        "mamaearth face wash men", "mamaearth vitamin c",
        "wow face wash", "wow sunscreen",
        "beardo face wash", "beardo ultraglow",
        "man company face wash", "mcaffeine face wash",
        "himalaya face wash men", "biotique face wash",
        "plum face wash", "dot and key sunscreen",
        "neutrogena face wash men", "clean and clear face wash",
        "lakme sun expert", "re equil sunscreen",
        // BUYING INTENT
        "best face wash for men", "best moisturizer for men",
        "best sunscreen for men", "best face cream for men",
        "best face serum for men", "face wash price",
        "moisturizer price for men", "sunscreen price",
        "best face wash for oily skin men", "best face wash for dry skin men",
        "face wash for pimples men", "face wash for dark spots",
        "best sunscreen under 500", "best face cream under 300",
        "best anti acne cream", "buy face wash online",
        "face cream price in india", "face serum price",
        "sunscreen spf 50 for face", "niacinamide serum for acne marks",
        "matte finish sunscreen", "pimple patches online",
        "men skincare combo pack online", "acne face wash for men price",
        "face wash for acne and pimples",
        // COMPARISON
        "minimalist vs derma co", "nivea vs garnier face wash",
        "cetaphil vs minimalist", "sunscreen spf 30 vs 50",
        "cetaphil moisturizer review", "best serum for beginners",
        "top 10 face wash for men", "sunscreen for sensitive skin",
        "garnier men face wash review",
        // PROBLEM
        "how to remove pimples", "how to remove dark spots",
        "oily skin care routine men", "dark circle cream for men",
        "tan removal for men", "acne treatment for men",
        "blackhead removal men", "how to reduce dark spots",
        "serum for open pores", "face cream for dry skin",
        "how to remove tan from face", "how to use face serum",
        "benefits of vitamin c serum", "how often should men wash face",
        "skincare routine for beginners", "what is niacinamide used for",
        "how to reduce acne naturally", "why is my skin oily",
        "daily skincare routine for men",
        // INGREDIENTS
        "vitamin c serum for men", "niacinamide for men",
        "retinol cream for men", "salicylic acid face wash men",
        "charcoal face wash men", "hyaluronic acid moisturizer",
        "glycolic acid face wash", "benzoyl peroxide face wash",
        "tea tree face wash", "aloe vera face wash men"
    ],

    'deodorants': [
        "deodorant", "body spray", "perfume for men", "deo for men",
        "roll on deodorant", "antiperspirant", "cologne",
        "body spray for men", "deodorant stick", "deodorant spray",
        "natural deodorant", "no gas deodorant", "pocket perfume",
        "deodorant roll on for men", "body mist for men",
        "long lasting deo", "deo spray", "deo stick",
        "deodorant for gym", "travel size deodorant",
        // BRANDS (massive volume category)
        "axe deodorant", "axe body spray", "axe dark temptation",
        "axe signature", "axe deo price",
        "fogg deodorant", "fogg body spray", "fogg deo price",
        "fogg marco", "fogg royal", "fogg fresh",
        "park avenue deodorant", "park avenue good morning",
        "park avenue cool blue", "park avenue body spray",
        "wild stone deodorant", "wild stone body spray",
        "wild stone night rider", "wild stone red",
        "denver deodorant", "denver body spray", "denver hamilton",
        "denver deo price", "denver caliber",
        "nivea deo men", "nivea roll on men", "nivea deep impact",
        "nivea fresh active", "nivea cool kick",
        "old spice deodorant", "old spice body spray", "old spice original",
        "engage deodorant", "engage body spray", "engage intensity",
        "engage click", "engage rush",
        "set wet deo", "set wet body spray", "set wet cool avatar",
        "yardley deodorant", "yardley gentleman",
        "brut deodorant", "brut original",
        "bella vita body spray", "villain body spray",
        "gatsby deo", "adidas deodorant men",
        "nike deodorant", "nautica deodorant",
        // BUYING INTENT
        "best deodorant for men", "best deo for men india",
        "long lasting deodorant for men", "deodorant for heavy sweating",
        "best body spray for men", "deodorant price",
        "deo combo offer", "body spray under 200",
        "body spray under 300", "best antiperspirant for men",
        "deodorant gift set men", "deo pack of 3",
        "best roll on for men", "buy deodorant online",
        "deo under 100", "long lasting body spray under 500",
        "best no gas deo", "best pocket perfume",
        // COMPARISON
        "roll on vs spray", "deodorant vs perfume difference",
        "deodorant vs antiperspirant", "fogg vs wild stone",
        "axe vs fogg", "park avenue vs denver",
        "nivea vs old spice deo", "body spray vs perfume",
        // PROBLEM / NEED
        "body odour solution", "excessive sweating remedy",
        "antiperspirant for heavy sweating", "how to reduce body odour",
        "best deo for body odour", "body odour treatment",
        "sweat proof deodorant", "aluminum free deodorant",
        "deodorant side effects", "dark underarms from deo",
        // SPECIFIC NEEDS
        "office wear deodorant", "deodorant for summer",
        "deodorant for winter", "sports deodorant men",
        "date night body spray", "fresh smelling deo men"
    ],

    'hair-oil': [
        "hair oil", "hair oil for men", "hair growth oil",
        "anti hair fall oil", "onion hair oil", "coconut hair oil",
        "almond hair oil", "castor oil for hair", "olive oil for hair",
        "argan oil for hair", "jojoba oil for hair",
        "bhringraj oil", "amla hair oil", "neem oil for hair",
        "tea tree oil for hair", "rosemary oil for hair",
        "hair oil for dandruff", "hot oil treatment", "light hair oil",
        "non sticky hair oil", "dry hair oil",
        // BRANDS
        "indulekha hair oil", "indulekha bringha oil",
        "parachute hair oil", "parachute advansed",
        "kesh king oil", "kesh king ayurvedic oil",
        "bajaj almond drops", "bajaj brahmi amla",
        "navratna hair oil", "navratna cool oil",
        "dabur amla hair oil", "dabur vatika hair oil",
        "wow hair oil", "wow onion hair oil",
        "biotique hair oil", "biotique bhringraj oil",
        "khadi hair oil", "khadi natural hair oil",
        "mamaearth onion hair oil", "mamaearth bhringraj oil",
        "man matters hair oil", "man matters minoxidil",
        "beardo hair oil", "ustraa hair oil",
        "himalaya hair oil", "trichup hair oil",
        "nihar naturals hair oil", "clinic plus hair oil",
        "set wet hair oil", "livon hair serum",
        // BUYING INTENT
        "best hair oil for men", "best oil for hair growth",
        "best hair oil for hair fall", "hair oil price",
        "non sticky hair oil men", "lightweight hair oil men",
        "best hair oil for dandruff", "best hair oil under 200",
        "best hair oil under 500", "hair oil combo pack",
        "buy hair oil online", "hair growth oil price",
        "indulekha oil price", "kesh king oil price",
        "onion hair oil price", "parachute oil price",
        // COMPARISON
        "indulekha vs kesh king", "coconut oil vs almond oil hair",
        "parachute vs indulekha", "onion oil vs castor oil",
        "minoxidil vs hair oil", "hair serum vs hair oil",
        // PROBLEM
        "hair fall solution", "hair fall control", "hair fall treatment",
        "dandruff treatment oil", "dry scalp treatment",
        "ayurvedic hair oil for growth", "hair thinning treatment",
        "rosemary oil for hair growth", "bhringraj oil benefits",
        "derma roller for hair", "minoxidil for hair growth",
        "prp treatment for hair", "scalp massage for hair growth",
        "how to reduce hair fall", "home remedies for hair fall",
        "diet for hair growth", "biotin for hair growth",
        // LONG TAIL
        "hair oil for thin hair", "hair oil for winter",
        "hot oil treatment for hair", "overnight hair oil treatment",
        "hair oil application tips", "best time to oil hair",
        "how often to oil hair", "cold pressed hair oil",
        "organic hair oil", "chemical free hair oil"
    ],

    'fragrance-premium': [
        "perfume for men", "eau de parfum men", "eau de toilette men",
        "cologne for men", "luxury perfume men", "attar",
        "body perfume for men", "branded perfume for men",
        "designer perfume men", "niche perfume", "oud perfume",
        "musk perfume", "woody perfume men", "fresh perfume men",
        "aquatic perfume men", "citrus perfume men",
        // BRANDS
        "titan skinn perfume", "titan skinn celeste", "titan skinn raw",
        "bellavita perfume", "bellavita ceo man", "bellavita dark",
        "villain perfume", "villain dark", "villain night",
        "beardo perfume", "beardo godfather",
        "ustraa cologne", "ustraa base camp",
        "wild stone edge", "wild stone perfume",
        "denver perfume", "denver pride", "denver honour",
        "fogg scent", "fogg xtremo",
        "engage perfume", "engage l'amante",
        "david beckham perfume", "davidoff perfume", "davidoff cool water",
        "calvin klein perfume", "ck one", "ck eternity",
        "versace perfume men", "versace pour homme",
        "armaf perfume", "armaf club de nuit",
        "rasasi perfume", "rasasi blue for men",
        "ajmal perfume", "ajmal carbon",
        "lattafa perfume", "embark perfume",
        "jaguar perfume", "police perfume",
        "united colors of benetton perfume", "guess perfume men",
        "nike perfume", "nautica voyage",
        "hugo boss perfume", "bvlgari perfume men",
        // BUYING INTENT
        "best perfume for men", "best perfume for men india",
        "best perfume under 500", "best perfume under 1000",
        "best perfume under 2000", "best perfume under 5000",
        "long lasting perfume men", "perfume gift set men",
        "buy perfume online", "perfume combo offer",
        "best edp for men india", "best cheap perfume men",
        "best luxury perfume india", "perfume price",
        "branded perfume under 1000",
        // SPECIFIC NEEDS
        "office wear perfume men", "date night perfume",
        "winter perfume men", "summer perfume men",
        "perfume for men wedding", "gym perfume men",
        "evening perfume men", "casual perfume men",
        // COMPARISON
        "perfume vs deodorant", "edp vs edt",
        "clone perfume india", "niche perfume india",
        "armaf vs david beckham", "titan skinn review",
        "bellavita review", "best clone perfumes india",
        // LONG TAIL
        "attar for men", "arabian perfume men",
        "french perfume men", "italian perfume men",
        "perfume layering tips", "how to make perfume last longer",
        "perfume notes explained", "sillage meaning",
        "projection perfume meaning", "beast mode perfume"
    ],

    'skincare-spec': [
        "face serum", "vitamin c serum", "niacinamide serum",
        "retinol serum", "hyaluronic acid serum", "salicylic acid serum",
        "eye cream", "under eye cream", "anti aging cream",
        "aha bha serum", "glycolic acid serum", "lactic acid serum",
        "peptide serum", "collagen serum", "alpha arbutin serum",
        "dark spot serum", "brightening serum", "acne serum",
        "anti pigmentation serum", "pore minimizing serum",
        // BRANDS
        "minimalist serum", "minimalist vitamin c", "minimalist niacinamide",
        "minimalist retinol", "minimalist alpha arbutin",
        "derma co serum", "derma co vitamin c", "derma co niacinamide",
        "derma co retinol", "derma co salicylic acid",
        "plum vitamin c serum", "plum niacinamide",
        "wow serum", "wow vitamin c",
        "mcaffeine face serum", "mcaffeine vitamin c",
        "dot and key serum", "dot and key vitamin c",
        "pilgrim serum", "pilgrim vitamin c",
        "chemist at play", "chemist at play serum",
        "the ordinary serum", "ordinary niacinamide",
        "olay serum", "olay retinol", "olay vitamin c",
        "garnier serum", "garnier vitamin c",
        "lakme serum", "ponds serum",
        // BUYING INTENT
        "best serum for men", "best vitamin c serum india",
        "best niacinamide serum", "best retinol serum india",
        "best dark circle cream men", "best anti aging serum india",
        "serum price", "vitamin c serum price",
        "niacinamide serum price", "retinol serum price",
        "best serum under 500", "best serum under 1000",
        "buy serum online", "serum combo offer",
        // PROBLEM / ROUTINE
        "skincare routine for men", "skincare for oily skin men",
        "anti aging routine men", "dark spots treatment",
        "pigmentation treatment face", "acne marks treatment",
        "how to use vitamin c serum", "how to use retinol",
        "niacinamide benefits", "hyaluronic acid benefits",
        "retinol benefits", "salicylic acid benefits",
        "when to use niacinamide", "niacinamide vs vitamin c",
        "can i use retinol daily", "retinol side effects",
        // SPECIFIC
        "serum for oily skin", "serum for dry skin",
        "serum for acne", "serum for glowing skin",
        "korean skincare men", "glass skin routine men",
        "serum for 20s", "serum for 30s",
        "morning skincare routine men", "night skincare routine men",
        "salicylic acid vs benzoyl peroxide"
    ],

    'shampoo': [
        "shampoo", "shampoo for men", "anti dandruff shampoo",
        "hair fall shampoo", "conditioner for men", "shampoo and conditioner",
        "dry shampoo", "color protect shampoo", "volumizing shampoo",
        "clarifying shampoo", "keratin shampoo", "biotin shampoo",
        "onion shampoo", "charcoal shampoo", "sulphate free shampoo",
        "paraben free shampoo", "organic shampoo", "herbal shampoo",
        "medicated shampoo", "ketoconazole shampoo",
        // BRANDS
        "head and shoulders shampoo", "head shoulders cool menthol",
        "dove shampoo men", "dove hair fall rescue",
        "tresemme shampoo", "tresemme keratin",
        "pantene shampoo", "pantene hair fall control",
        "clinic plus shampoo", "sunsilk shampoo",
        "wow shampoo", "wow apple cider vinegar shampoo",
        "mamaearth shampoo", "mamaearth onion shampoo",
        "biotique shampoo", "biotique green apple shampoo",
        "nivea men shampoo", "nivea deep clean shampoo",
        "loreal shampoo men", "loreal fall resist",
        "clear shampoo men", "clear cool sport menthol",
        "park avenue beer shampoo", "khadi shampoo",
        "himalaya shampoo", "himalaya anti hair fall",
        "dove men care shampoo", "tresemme men",
        "man matters shampoo", "beardo shampoo",
        "ustraa shampoo", "garnier men shampoo",
        // BUYING INTENT
        "best shampoo for men", "best shampoo for hair fall",
        "best anti dandruff shampoo", "best shampoo for dry hair",
        "best shampoo for oily hair", "shampoo price",
        "best shampoo under 200", "best shampoo under 500",
        "best sulphate free shampoo", "shampoo combo offer",
        "buy shampoo online", "best conditioner for men",
        "best 2 in 1 shampoo", "shampoo for colored hair men",
        // COMPARISON
        "head and shoulders vs clear", "wow vs mamaearth shampoo",
        "nivea vs dove shampoo men", "sulphate vs sulphate free",
        // PROBLEM
        "dandruff treatment shampoo", "hair fall control shampoo",
        "dry scalp shampoo", "itchy scalp treatment",
        "anti fungal shampoo", "oily scalp shampoo",
        "shampoo for thin hair men", "shampoo for thick hair",
        "how often to shampoo", "co washing for men",
        // LONG TAIL
        "2 in 1 shampoo and conditioner men", "travel size shampoo",
        "baby shampoo for adults", "ph balanced shampoo",
        "scalp scrub for men", "hair mask for men",
        "deep conditioning treatment men", "leave in conditioner men"
    ],

    'soap': [
        "soap", "body wash", "shower gel", "bathing soap",
        "body wash for men", "soap for men", "liquid soap",
        "bar soap", "handmade soap", "organic soap",
        "antibacterial soap", "moisturizing soap", "glycerin soap",
        "charcoal soap", "neem soap", "turmeric soap",
        "exfoliating soap", "whitening soap",
        // BRANDS
        "dove soap men", "dove body wash men", "dove care protect",
        "nivea body wash men", "nivea deep impact body wash",
        "nivea active clean", "nivea men shower gel",
        "pears soap", "pears body wash",
        "dettol soap", "dettol body wash", "dettol cool",
        "lifebuoy soap", "lifebuoy body wash",
        "lux soap", "lux body wash",
        "fiama shower gel", "fiama men shower gel",
        "park avenue soap", "park avenue body wash",
        "cinthol soap", "cinthol shower gel", "cinthol cool",
        "yardley soap", "yardley gentleman",
        "medimix soap", "medimix ayurvedic",
        "wild stone soap", "wild stone body wash",
        "old spice body wash", "old spice shower gel",
        "beardo body wash", "ustraa body wash",
        "the man company body wash", "mcaffeine body wash",
        "himalaya neem soap", "santoor soap",
        "mysore sandal soap", "khadi soap",
        // BUYING INTENT
        "best body wash for men", "best soap for men",
        "best shower gel for men", "body wash price",
        "soap for dry skin men", "soap for oily skin",
        "best antibacterial soap", "best moisturizing soap",
        "body wash under 200", "body wash under 500",
        "soap combo pack", "buy body wash online",
        "best charcoal soap", "best neem soap",
        // COMPARISON
        "body wash vs soap", "shower gel vs soap",
        "liquid soap vs bar soap", "dove vs nivea body wash",
        "dettol vs lifebuoy", "bar soap vs liquid soap benefits",
        // PROBLEM
        "soap for acne body", "soap for back acne",
        "soap for body odour", "soap for sensitive skin men",
        "soap for dark skin", "soap for dry skin winter",
        "exfoliating body wash men", "keratosis pilaris body wash"
    ],

    'body-lotion': [
        "body lotion", "body lotion for men", "body cream",
        "moisturizer for body", "body butter", "body milk",
        "body lotion for dry skin", "body lotion for winter",
        "body lotion with spf", "night body lotion",
        "non greasy body lotion", "lightweight body lotion",
        "whitening body lotion", "anti aging body lotion",
        "cocoa butter lotion", "shea butter lotion",
        "aloe vera body lotion", "vitamin e body lotion",
        // BRANDS
        "nivea body lotion men", "nivea deep moisture",
        "nivea cocoa nourish", "nivea aloe hydration",
        "vaseline body lotion", "vaseline intensive care",
        "vaseline cocoa glow", "vaseline healthy white",
        "dove body lotion", "dove deeply nourishing",
        "ponds body lotion", "ponds moisturizing",
        "wow body lotion", "wow coconut body lotion",
        "biotique body lotion", "biotique morning nectar",
        "himalaya body lotion", "himalaya cocoa butter",
        "plum body lotion", "plum hawaiian rumba",
        "parachute body lotion", "parachute advansed body lotion",
        "boroplus cream", "boroplus body lotion",
        "jergens body lotion", "aveeno body lotion",
        "cetaphil body lotion", "eucerin body lotion",
        "the man company body lotion", "beardo body lotion",
        // BUYING INTENT
        "best body lotion for men", "best body lotion for dry skin",
        "best body lotion for winter", "body lotion price",
        "non greasy body lotion men", "lightweight body lotion men",
        "best body lotion under 200", "best body lotion under 500",
        "buy body lotion online", "body lotion combo offer",
        "best moisturizer for men body", "best winter cream for men",
        // COMPARISON
        "body lotion vs body cream", "body lotion vs body butter",
        "nivea vs vaseline body lotion", "cocoa butter vs shea butter",
        "body oil vs body lotion",
        // PROBLEM / NEED
        "dry skin treatment men", "winter skin care men",
        "body lotion for summer", "after shower lotion",
        "moisturizer for rough skin", "cracked skin remedy",
        "dry elbows treatment", "ashy skin treatment men",
        "itchy skin after shower", "winter itch remedy",
        // LONG TAIL
        "spf body lotion men", "tinted body lotion men",
        "body lotion with sunscreen", "fragrance body lotion men",
        "calamine lotion", "after sun lotion",
        "body lotion for tattoo", "intensive repair lotion"
    ],

    'talcum': [
        "talcum powder", "body powder", "prickly heat powder",
        "cooling powder", "dusting powder", "medicated powder",
        "baby powder for men", "after shower powder",
        "anti fungal powder", "sweat absorbing powder",
        "body odour powder", "chafing powder",
        "talc free powder", "corn starch powder body",
        // BRANDS
        "ponds powder", "ponds magic powder", "ponds dream flower",
        "yardley powder", "yardley english lavender",
        "navratna powder", "navratna cool talc",
        "dermicool powder", "dermicool prickly heat",
        "nycil powder", "nycil cool classic",
        "wild stone talc", "wild stone powder",
        "denver talc", "denver hamilton talc",
        "park avenue talc", "park avenue cool blue talc",
        "engage talc", "engage intensity talc",
        "cinthol talc", "cinthol cool powder",
        "set wet powder", "set wet cool powder",
        "old spice talc", "nivea men talc",
        "spinz talc", "shower to shower powder",
        "johnson baby powder",
        // BUYING INTENT
        "best talcum powder for men", "best prickly heat powder",
        "best cooling powder", "powder price",
        "talc free body powder", "best powder for summer",
        "body powder under 100", "body powder under 200",
        "buy talcum powder online", "powder combo offer",
        "best medicated powder", "best anti fungal powder",
        // PROBLEM / NEED
        "prickly heat treatment", "body odour powder",
        "sweat absorbing powder", "anti fungal powder for body",
        "rash powder for men", "chafing powder for thighs",
        "heat rash powder", "skin rash powder",
        "body powder for gym", "powder for sweaty hands",
        // SEASONAL / SPECIFIC
        "summer powder for men", "cooling powder for summer",
        "talcum powder for gym", "after shower powder men",
        "medicated powder for men", "mentholated body powder",
        "powder for underarms", "powder for feet",
        "antifungal foot powder", "shoe powder for odour",
        // SAFETY
        "talcum powder safe", "talc vs corn starch",
        "talcum powder side effects", "talc free alternatives",
        "is talcum powder harmful", "natural body powder"
    ],

    'oral-care': [
        "toothpaste", "toothbrush", "mouthwash", "electric toothbrush",
        "teeth whitening", "tongue cleaner", "dental floss",
        "toothpaste for sensitive teeth", "whitening toothpaste",
        "charcoal toothpaste", "herbal toothpaste", "fluoride toothpaste",
        "kids toothpaste", "gum care toothpaste", "cavity protection toothpaste",
        "water flosser", "interdental brush", "teeth whitening strips",
        "teeth whitening kit", "dental care products",
        // BRANDS
        "colgate toothpaste", "colgate maxfresh", "colgate total",
        "colgate visible white", "colgate charcoal",
        "sensodyne toothpaste", "sensodyne rapid relief",
        "sensodyne pronamel", "sensodyne fresh mint",
        "pepsodent toothpaste", "pepsodent germicheck",
        "closeup toothpaste", "closeup ever fresh",
        "oral b toothbrush", "oral b electric toothbrush",
        "oral b vitality", "oral b pro",
        "dabur red toothpaste", "dabur meswak",
        "patanjali toothpaste", "patanjali dant kanti",
        "himalaya toothpaste", "himalaya complete care",
        "vicco toothpaste", "vicco vajradanti",
        "listerine mouthwash", "listerine cool mint",
        "colgate mouthwash", "colgate plax",
        "hextidine mouthwash", "betadine mouthwash",
        "philips sonicare", "quip toothbrush",
        // BUYING INTENT
        "best toothpaste", "best toothpaste for sensitive teeth",
        "best electric toothbrush india", "best mouthwash india",
        "toothpaste price", "electric toothbrush price",
        "best toothpaste for whitening", "best toothpaste under 100",
        "best mouthwash for bad breath", "best tongue cleaner",
        "buy electric toothbrush online", "oral b price",
        "teeth whitening kit price", "dental floss price",
        "best whitening toothpaste india",
        // PROBLEM
        "teeth whitening at home", "yellow teeth treatment",
        "bad breath solution", "gum disease treatment",
        "sensitive teeth remedy", "cavity prevention",
        "bleeding gums treatment", "tooth decay prevention",
        "how to whiten teeth naturally", "how to fix yellow teeth",
        "toothache remedy", "mouth ulcer treatment",
        "receding gums treatment", "plaque removal at home",
        // LONG TAIL
        "activated charcoal toothpaste", "baking soda toothpaste",
        "toothpaste for braces", "toothpaste for smokers",
        "ayurvedic toothpaste", "neem toothpaste",
        "salt toothpaste", "enzyme toothpaste",
        "oil pulling benefits", "coconut oil for teeth"
    ]
};

export function getCuratedSeeds(categoryId: string): string[] {
    return CURATED_SEEDS[categoryId] || [];
}
